# Generated by Django 4.2 on 2023-04-22 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_of_brith',
            new_name='date_of_birth',
        ),
    ]
